export type Overrides = {
  [Name in keyof ComponentNameToClassKey]?: Partial<
    StyleRules<ComponentNameToClassKey[Name]>
  >
};

type ComponentNameToClassKey = {
  MuiAppBar: any;
  MuiAvatar: any;
  MuiBackdrop: any;
  MuiBadge: any;
  MuiBottomNavigation: any;
  MuiBottomNavigationAction: any;
  MuiButton: any;
  MuiButtonBase: any;
  // MuiCard: any;
  MuiCardActions: any;
  MuiCardContent: any;
  MuiCardHeader: any;
  MuiCardMedia: any;
  MuiCheckbox: any;
  MuiChip: any;
  MuiCircularProgress: any;
  MuiCollapse: any;
  MuiDialog: any;
  MuiDialogActions: any;
  MuiDialogContent: any;
  MuiDialogContentText: any;
  MuiDialogTitle: any;
  MuiDivider: any;
  MuiDrawer: any;
  MuiExpansionPanel: any;
  MuiExpansionPanelActions: any;
  MuiExpansionPanelDetails: any;
  MuiExpansionPanelSummary: any;
  MuiFormControl: any;
  MuiFormControlLabel: any;
  MuiFormGroup: any;
  MuiFormHelperText: any;
  MuiFormLabel: any;
  MuiGrid: any;
  MuiGridList: any;
  MuiGridListTile: any;
  MuiGridListTileBar: any;
  MuiIcon: any;
  MuiIconButton: any;
  MuiInput: any;
  MuiInputAdornment: any;
  MuiInputLabel: any;
  MuiLinearProgress: any;
  MuiList: any;
  MuiListItem: any;
  MuiListItemAvatar: any;
  MuiListItemIcon: any;
  MuiListItemSecondaryAction: any;
  MuiListItemText: any;
  MuiListSubheader: any;
  MuiMenu: any;
  MuiMenuItem: any;
  // MuiMenuList: any;
  MuiMobileStepper: any;
  MuiModal: any;
  MuiPaper: any;
  MuiPopover: any;
  MuiRadio: any;
  // MuiRadioGroup: any;
  MuiSelect: any;
  // MuiSelectInput: any;
  MuiSnackbar: any;
  MuiSnackbarContent: any;
  MuiStep: any;
  MuiStepButton: any;
  MuiStepConnector: any;
  MuiStepContent: any;
  MuiStepIcon: any;
  MuiStepLabel: any;
  MuiStepper: any;
  MuiSvgIcon: any;
  MuiSwitchBase: any;
  MuiSwitch: any;
  MuiTab: any;
  MuiTabIndicator: any;
  MuiTable: any;
  MuiTableCell: any;
  MuiTablePagination: any;
  MuiTableRow: any;
  MuiTableSortLabel: any;
  MuiTabs: any;
  MuiTabScrollButton: any;
  MuiTextarea: any;
  // MuiTextField: any;
  MuiToolbar: any;
  MuiTooltip: any;
  MuiTouchRipple: any;
  MuiTypography: any;
};
